sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - postgresql
env:
  - LINDEN_HONEY_DB_NAME=linden_honey_local LINDEN_HONEY_DB_USER_LOGIN=postgres
before_script:
  - psql -c 'create database linden_honey_local;' -U postgres
