sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.6"
services:
  - postgresql
env:
  - LINDEN_HONEY_DB_URL=jdbc:postgresql://localhost:5432/lindenhoney?user=postgres
before_script:
  - psql -c 'create database lindenhoney;' -U postgres
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
