version: "3"

services:
  db:
    container_name: linden-honey-spring-db
    image: "postgres:latest"
    environment:
     - POSTGRES_USER=linden_honey_local
     - POSTGRES_PASSWORD=linden_honey_local
     - POSTGRES_DB=linden_honey_local
    expose:
     - "5432"
    networks:
      - linden-honey-spring-net
  app:
    container_name: linden-honey-spring-app
    build: .
    ports:
     - "8080:8080"
    networks:
      - linden-honey-spring-net
    links:
     - db
    environment:
     - LINDEN_HONEY_DB_URL=postgresql://db:5432/linden_honey_local

networks:
  linden-honey-spring-net:
    driver: bridge
