version: '3'
services:
  db:
    container_name: linden-honey-db
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=linden-honey
      - MONGODB_PASSWORD=linden-honey
      - MONGODB_DATABASE=linden-honey
    ports:
      - 27017:27017
    volumes:
      - linden-honey-db-data:/data/db
    networks:
      - linden-honey-net
  app:
    container_name: linden-honey-app
    image: lindenhoney/linden-honey
    build: .
    environment:
     - LINDEN_HONEY_DB_URI=mongodb://linden-honey:linden-honey@db:27017/linden-honey
     - LINDEN_HONEY_APP_PROFILES=dev
    ports:
      - 8080:8080
    networks:
      - linden-honey-net
    links:
     - db

volumes:
  linden-honey-db-data:

networks:
  linden-honey-net:
    driver: bridge
