version: "3"

services:
  db:
    container_name: linden-honey-spring-db
    image: "postgres:latest"
    environment:
     - POSTGRES_USER=linden-honey
     - POSTGRES_PASSWORD=linden-honey
     - POSTGRES_DB=linden-honey
    ports:
     - "5432:5432"
    networks:
      - linden-honey-spring-net
  app:
    container_name: linden-honey-spring-app
    image: lindenhoney/linden-honey-spring
    build: .
    ports:
     - "8080:8080"
    networks:
      - linden-honey-spring-net
    links:
     - db
    environment:
     - LINDEN_HONEY_DB_URL=postgresql://db:5432/linden-honey?user=linden-honey&password=linden-honey

networks:
  linden-honey-spring-net:
    driver: bridge
