version: "3"

services:
  db:
    container_name: linden-honey-db
    image: "mongo:latest"
    ports:
     - "27017:27017"
    volumes:
        - linden-honey-db-data:/data/db
    networks:
      - linden-honey-net
  app:
    container_name: linden-honey-app
    image: lindenhoney/linden-honey
    build: .
    ports:
     - "8080:8080"
    networks:
      - linden-honey-net
    links:
     - db
    environment:
     - LINDEN_HONEY_DB_URL=mongodb://db:27017/linden-honey
     - LINDEN_HONEY_APP_PROFILES=dev

volumes:
  linden-honey-db-data:

networks:
  linden-honey-net:
    driver: bridge
