# ===============================
# [ TG2VK Properties ]
# ===============================
linden_honey:
  app:
    name: Linden Honey
  db:
    url: mongodb://linden-honey:linden-honey@localhost:27017/linden-honey


# ===============================
# [ Spring Properties ]
# ===============================
spring:
  application:
    name: ${linden_honey.app.name}
  data:
    mongodb:
      uri: ${linden_honey.db.url}

# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        lindenhoney: DEBUG
    org:
      springframework: INFO
