application:
  data:
    loaders:
      enabled: false
      remote:
        url: https://gist.githubusercontent.com/alebabai/968b042e94f6b0ab9c33a4e75276d352/raw/517e185ca56575783ba94b1f2455a60def6d4671/letov.min.json
  rest:
    base-path: /api

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linden-honey?user=linden-honey&password=linden-honey
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs

logging:
  level:
    com:
      github:
        lindenhoney: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
      flywaydb: INFO
