# ===============================
# [ TG2VK Properties ]
# ===============================
linden_honey:
  app:
    name: Linden Honey
  db:
    url: postgresql://localhost:5433/linden_honey_local?user=linden_honey_local&password=linden_honey_local


# ===============================
# [ Spring Properties ]
# ===============================
spring:
  application:
    name: ${linden_honey.app.name}
  datasource:
    url: jdbc:${linden_honey.db.url}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true


# ===============================
# [ Flyway Properties ]
# ===============================
flyway:
  enabled: true
  locations: classpath:db/migration


# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        alebabai:
          lindenhoney: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
      flywaydb: INFO
