application:
  rest:
    base-path: /api

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linden-honey?user=linden-honey&password=linden-honey
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs

logging:
  level:
    com:
      github:
        lindenhoney: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
      flywaydb: INFO
