# ===============================
# [ Linden Honey Properties ]
# ===============================
linden-honey:
  app:
    name: Linden Honey
    port: 8080
    profiles: dev
  db:
    url: mongodb://linden-honey:linden-honey@localhost:27017/linden-honey


# ===============================
# [ Server Properties ]
# ===============================
server:
  port: ${linden-honey.app.port}


# ===============================
# [ Spring Properties ]
# ===============================
spring:
  profiles:
    active: ${linden-honey.app.profiles}
  application:
    name: ${linden-honey.app.name}
  data:
    mongodb:
      uri: ${linden-honey.db.url}


# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        lindenhoney: DEBUG
    org:
      springframework: INFO
